// Sample blog posts — bilingual (JP/EN) mix of daily life + tech
window.POSTS = [
  {
    id: 'p08',
    slug: 'rethinking-my-terminal-setup',
    title_en: 'Rethinking my terminal setup after 5 years',
    title_jp: '5年ぶりにターミナル環境を見直した',
    date: '2026-04-17',
    readMin: 8,
    tags: ['dev', 'tools', 'zsh'],
    lang: 'bi',
    category: 'tech',
    excerpt_en: 'Ditched oh-my-zsh, wrote ~60 lines of plain zsh config, and never looked back. Here is what actually mattered.',
    excerpt_jp: 'oh-my-zshをやめて、素のzshを60行ほど書いた。本当に必要だったものだけの記録。',
    body: [
      { type: 'p', en: 'I have been using oh-my-zsh since 2021. It was fine. Until I opened a new terminal and it took 1.2 seconds.', jp: '2021年からずっとoh-my-zshを使っていた。特に不満もなかった。新しいタブを開くのに1.2秒かかるまでは。' },
      { type: 'h2', en: 'The diagnosis', jp: '原因を探る' },
      { type: 'p', en: 'zsh -xv pointed at 14 plugins I had not touched in years. Git prompt alone was spawning 3 subprocesses per prompt.', jp: '`zsh -xv`を走らせたら、もう何年も触っていない14個のプラグインが出てきた。gitプロンプトだけで3回subprocessを呼んでいた。' },
      { type: 'code', lang: 'zsh', content: "# before\nplugins=(git docker kubectl aws node npm yarn\n         golang rust python pip pyenv\n         nvm tmux history-substring-search)\n\n# after\nautoload -Uz compinit && compinit -C\nsetopt AUTO_CD HIST_IGNORE_DUPS SHARE_HISTORY" },
      { type: 'h2', en: 'The result', jp: '結果' },
      { type: 'p', en: 'Startup went from 1.2s to 0.08s. I lost zero features I actually used.', jp: '起動時間が1.2秒→0.08秒。失った機能は、実際に使っていたものはゼロ。' },
    ],
    comments: [
      { author: 'mika', date: '2026-04-17', text: 'starship使ってないの?' },
      { author: 'you', date: '2026-04-17', text: '使ってる!プロンプトはstarship。コマンド補完やキーバインドだけ素のzshに戻した感じ。' },
      { author: 'devops_guy', date: '2026-04-18', text: 'Same journey here. `compinit -C` is magic.' },
    ],
  },
  {
    id: 'p07',
    slug: 'coffee-shop-kanazawa',
    title_en: 'A coffee shop in Kanazawa that I cannot forget',
    title_jp: '金沢で忘れられない喫茶店の話',
    date: '2026-04-12',
    readMin: 4,
    tags: ['travel', 'coffee', 'diary'],
    lang: 'jp',
    category: 'life',
    excerpt_en: 'Found a 40-year-old kissaten behind the castle. The master remembered my order from a year ago.',
    excerpt_jp: '金沢城の裏手で見つけた、40年続く喫茶店。一年前の注文をマスターが覚えていた。',
    body: [
      { type: 'p', jp: '金沢に行ったのは去年の春だった。雨が強くて、傘もさせないほどで、とりあえず近くの店に駆け込んだ。', en: 'Last spring in Kanazawa. The rain was heavy enough that umbrellas were useless, so I ducked into the nearest place.' },
      { type: 'p', jp: '扉を開けると、深煎りの香りと、古いレコードの音。マスターは何も言わずにカウンター席を指さした。', en: 'Dark roast, an old vinyl spinning. The master silently pointed me at the counter.' },
    ],
    comments: [
      { author: 'ken', date: '2026-04-13', text: '店の名前教えてほしい…!' },
    ],
  },
  {
    id: 'p06',
    slug: 'learning-go-weekend',
    title_en: 'What I learned from building a CLI in Go over a weekend',
    title_jp: '週末にGoでCLIを作って学んだこと',
    date: '2026-04-05',
    readMin: 11,
    tags: ['go', 'dev', 'cli'],
    lang: 'bi',
    category: 'tech',
    excerpt_en: 'cobra is overkill for most things. flag + a single main.go got me 90% of the way.',
    excerpt_jp: 'cobraは大体のケースでやりすぎ。flag一枚とmain.goで9割いける。',
  },
  {
    id: 'p05',
    slug: 'march-reading-list',
    title_en: 'March reading list: three books that stuck',
    title_jp: '3月に読んだ本、記憶に残った3冊',
    date: '2026-03-31',
    readMin: 6,
    tags: ['books', 'diary'],
    lang: 'bi',
    category: 'life',
    excerpt_en: 'One fiction, one on distributed systems, one poetry collection. A surprisingly coherent month.',
    excerpt_jp: '小説1冊、分散システムの本1冊、詩集1冊。妙に一貫した月だった。',
  },
  {
    id: 'p04',
    slug: 'debugging-memory-leak-prod',
    title_en: 'Debugging a memory leak in production at 2am',
    title_jp: '深夜2時、本番でメモリリークを追った話',
    date: '2026-03-22',
    readMin: 14,
    tags: ['dev', 'sre', 'war-story'],
    lang: 'en',
    category: 'tech',
    excerpt_en: 'pprof is good. pprof + a sleep-deprived brain is also good, just slower. A postmortem.',
    excerpt_jp: 'pprofは良い。睡眠不足の脳 + pprofも良いが、遅い。ポストモーテム。',
  },
  {
    id: 'p03',
    slug: 'garden-balcony-year1',
    title_en: 'One year of balcony gardening: what survived',
    title_jp: 'ベランダ菜園1年目、生き残ったやつら',
    date: '2026-03-14',
    readMin: 5,
    tags: ['garden', 'diary'],
    lang: 'jp',
    category: 'life',
    excerpt_en: 'Basil: thriving. Tomatoes: tragic. Mint: now ruling the balcony.',
    excerpt_jp: 'バジルは大豊作。トマトは悲劇。ミントはベランダを支配している。',
  },
  {
    id: 'p02',
    slug: 'why-i-left-twitter',
    title_en: 'Why I finally left Twitter (and what I replaced it with)',
    title_jp: 'Twitterをついにやめた理由と、代わりに始めたこと',
    date: '2026-03-02',
    readMin: 7,
    tags: ['internet', 'diary', 'meta'],
    lang: 'bi',
    category: 'life',
    excerpt_en: 'RSS, a notes.app, and this blog. Less dopamine, more signal.',
    excerpt_jp: 'RSS、メモ帳、そしてこのブログ。ドーパミンは減って、シグナルが増えた。',
  },
  {
    id: 'p01',
    slug: 'hello-world',
    title_en: 'hello, world — starting this blog',
    title_jp: 'hello, world — このブログを始めます',
    date: '2026-02-20',
    readMin: 3,
    tags: ['meta'],
    lang: 'bi',
    category: 'life',
    excerpt_en: 'A space for half-finished thoughts, code, and small observations. In two languages.',
    excerpt_jp: '書きかけの考え、コード、ちいさな観察。二つの言葉で書く場所。',
  },
];

window.PROFILE = {
  handle: 'kenji',
  name_en: 'Kenji',
  name_jp: 'けんじ',
  bio_en: 'Backend engineer in Tokyo. Writing about code, coffee, and the space between.',
  bio_jp: '東京でバックエンドエンジニアをしています。コード、珈琲、その間にあるものについて。',
  links: [
    { label: 'github', href: '#', handle: '@kenji' },
    { label: 'mastodon', href: '#', handle: '@kenji@hachyderm.io' },
    { label: 'rss', href: '#', handle: '/feed.xml' },
    { label: 'email', href: '#', handle: 'hi@kenji.dev' },
  ],
};
